var TRIP_STATUS = {
  RECRUITING: "recruiting",
  FULL: "full",
  DEPARTED: "departed",
  COMPLETED: "completed",
  CANCELLED: "cancelled"
};

var TRIP_STATUS_TEXT = {};
TRIP_STATUS_TEXT[TRIP_STATUS.RECRUITING] = "招募中";
TRIP_STATUS_TEXT[TRIP_STATUS.FULL] = "已满员";
TRIP_STATUS_TEXT[TRIP_STATUS.DEPARTED] = "已出发";
TRIP_STATUS_TEXT[TRIP_STATUS.COMPLETED] = "已完成";
TRIP_STATUS_TEXT[TRIP_STATUS.CANCELLED] = "已取消";

var APPLICATION_STATUS = {
  PENDING: "pending",
  CONFIRMED: "confirmed",
  REJECTED: "rejected",
  CANCELLED: "cancelled"
};

var PASSENGER_STATUS_TEXT = {};
PASSENGER_STATUS_TEXT[APPLICATION_STATUS.PENDING] = "待确认";
PASSENGER_STATUS_TEXT[APPLICATION_STATUS.CONFIRMED] = "已确认";
PASSENGER_STATUS_TEXT[APPLICATION_STATUS.REJECTED] = "已拒绝";
PASSENGER_STATUS_TEXT[APPLICATION_STATUS.CANCELLED] = "已取消";

var TRIP_TAGS = ["高速直达", "优先女生", "可带宠物", "可带大件行李", "不抽烟", "听音乐", "安静"];

var ERROR_CODE = {
  SUCCESS: 0, PARAM_ERROR: 1001, NOT_LOGIN: 1002, NOT_VERIFIED: 1003, NO_PERMISSION: 1004,
  TRIP_NOT_FOUND: 2001, TRIP_FULL: 2002, TRIP_CANCELLED: 2003, TRIP_EXPIRED: 2004,
  DUPLICATE_APPLY: 3001, SELF_APPLY: 3002, SYSTEM_ERROR: 4001, RATE_LIMIT: 5001
};

module.exports = {
  TRIP_STATUS: TRIP_STATUS, TRIP_STATUS_TEXT: TRIP_STATUS_TEXT,
  APPLICATION_STATUS: APPLICATION_STATUS, PASSENGER_STATUS_TEXT: PASSENGER_STATUS_TEXT,
  TRIP_TAGS: TRIP_TAGS, ERROR_CODE: ERROR_CODE
};
